//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCF_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCF_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =-=-=-=-=-V1.4(14/03/2015)-=-=-=-=-= *PUBLIC-STABLE*
        ///+ Now supports FHA .fcf files too!
        ///+ Added some more tooltips!
        ///+ Added the ability to resize the text log on right side!
        ///+ Re-designed the About screen again!
        ///+ Added a &apos;Save&apos; and a &apos;Save As&apos; feature!
        ///+ Improved the UI!
        ///+ Added a &apos;Remove&apos; button, along with &apos;Delete&apos; keycode, to remove flow elements!
        ///+ Now, Ctrl+R also refreshes the flowchart!
        ///+ Saving automatically re-loads the file too!
        ///- Fixed a positioning bug, when moving and saving flow ele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse_hightlight {
            get {
                object obj = ResourceManager.GetObject("collapse_hightlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_highlight {
            get {
                object obj = ResourceManager.GetObject("expand_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart Editor is a tool designed to edit .fcf files, used by the TypeMoon modified version of Kirikiri, in short a game&apos;s custom script editing tool...
        ///
        ///Features:
        ///* Easy to use interface!
        ///* 3 ways to open the files: Double-clicking .fcf files, dragging and dropping .fcf files on the program window, or using Ctrl + O/File-&gt;Open to browse to the file.
        ///* Move-able Flow elements!
        ///* Ability to edit SCENEs, SELECTERs and OUTERLABELs.
        ///* Requires variable.txt to be able to select flags.
        ///
        ///Credits:
        ///* Ide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==&gt;FSN
        ///セイバー好感度|Saber&apos;s Point
        ///桜好感度|Sakura&apos;s Point
        ///凛好感度|Rin&apos;s Point
        ///イリヤ好感度|Illya&apos;s Point
        ///道場説明|Dojo Explained?
        ///gセイバークリア|Saber Route Cleared?
        ///g桜クリア|Sakura Route Cleared?
        ///g桜トゥルー|Got &apos;Sakura True&apos; ending?
        ///g桜ノーマル|Got &apos;Sakura Normal&apos; ending?
        ///g凛クリア|Rin Route Cleared?
        ///桜ルート分岐|Sakura&apos;s Route Points
        ///士郎の痣|Shirou&apos;s Bruise
        ///ソロ|Working Solo?
        ///質問１|Question 1 asked from Saber?
        ///質問２|Question 2 asked from Saber?
        ///質問３|Question 3 asked from Saber?
        ///自然治癒を知らない|No Self-Healing
        ///不勇の罪|Coward
        ///セイバー不在|Saber Gone?
        ///イリヤとの会話|Il [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string variables {
            get {
                return ResourceManager.GetString("variables", resourceCulture);
            }
        }
    }
}
